from .nodes import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_BASE
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_BASE
from .controlnet_nodes import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_CONTROLNET
from .controlnet_nodes import NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_CONTROLNET

# Merge the dictionaries
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_BASE, **NODE_CLASS_MAPPINGS_CONTROLNET}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_BASE, **NODE_DISPLAY_NAME_MAPPINGS_CONTROLNET}

